version: '3'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./work:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    # イメージ名をカスタマイズ
    image: laravelpj/php
    container_name: "laravel-php"
    volumes:
      # コンテナ側のディレクトリ名は、nginx側と揃ってないと動かない
      - ./work:/work

  mysql:
    image: mysql:5.7
    container_name: "laravel-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: "Asia/Tokyo"
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf/master.cnf:/etc/mysql/conf.d/my.cnf

  mysql-slave:
    image: mysql:5.7
    container_name: "laravel-mysql-slave"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: "Asia/Tokyo"
    ports:
      - 13307:3306
    depends_on:
      - mysql
    volumes:
      - ./docker/mysql/conf/slave.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/shell/start-slave.sh:/docker-entrypoint-initdb.d/start-slave.sh

  postgres:
    image: postgres:alpine
    container_name: "laravel-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 16379:6379
