version: '3.4'

# mysqlの共通設定
x-template: &mysql-template
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: "Asia/Tokyo"

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./work:/work:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    # イメージ名をカスタマイズ
    image: laravelpj/php
    container_name: "laravel-php"
    volumes:
      # コンテナ側のディレクトリ名は、nginx側と揃ってないと動かない
      - ./work:/work:cached
      # 各種設定ファイル
      - ./docker/php/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  mysql-master:
    <<: *mysql-template
    container_name: "laravel-mysql-master"
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf/master.cnf:/etc/mysql/conf.d/my.cnf
      # 永続化をしたくない場合はコメントアウト
      - ./work/.docker/mysql/master/data:/var/lib/mysql:cached
      - ./work/.docker/mysql/master/log:/var/log/mysql:cached

  mysql-slave:
    <<: *mysql-template
    container_name: "laravel-mysql-slave"
    ports:
      - 13307:3306
    depends_on:
      - mysql-master
    volumes:
      - ./docker/mysql/conf/slave.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/shell/start-slave.sh:/docker-entrypoint-initdb.d/start-slave.sh
      # レプリケーション設定がおかしくなってしまうので、Slaveの/var/lib/mysqlは永続化しない
      - ./work/.docker/mysql/slave/log:/var/log/mysql:cached

  # postgres:
  #   image: postgres:alpine
  #   container_name: "laravel-postgres"
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #   ports:
  #     - 15432:5432

  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 16379:6379
    # 永続化をしたくない場合はコメントアウト
    command: redis-server --appendonly yes
    volumes:
      - ./work/.docker/redis/data:/data:cached
