version: '3'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./work:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    # イメージ名をカスタマイズ
    image: laravelpj/php
    container_name: "laravel-php"
    volumes:
      # コンテナ側のディレクトリ名は、nginx側と揃ってないと動かない
      - ./work:/work

  mysql:
    image: mysql:5.7
    container_name: "laravel-mysql"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:alpine
    container_name: "laravel-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 16379:6379
